#!/apps/free/python/2.7.10/bin/python

# defines the value of the parameters that will be used by testFullbG.py
# generated by KScript.py

interactive = False

params = {'nbcpu':    8,
          'nbCh' :    100,
          'LG14modelID':  9,
          'whichTest': 'testChannelBG', # which test was used to generate the log
          'nbMSN':    2644.000000,
          'nbFSI':    53.000000,
          'nbSTN':    8.000000,
          'nbGPe':    25.000000,
          'nbGPi':    14.000000,
          'nbCSN':    3000.000000,
          'nbPTN':    100.000000,
          'nbCMPf':   9.000000,
          'GMSN':     4.00,
          'GFSI':     1.00,
          'GSTN':     1.40,
          'GGPe':     1.00,
          'GGPi':     1.00, 
          'IeGPe':    11.0,
          'IeGPi':    11.0,
          'inDegCSNMSN': 100.,
          'inDegPTNMSN':   1.,
          'inDegCMPfMSN':  1.,
          'inDegFSIMSN':  30., # according to Humphries et al. 2010, 30-150 FSIs->MSN
          'inDegMSNMSN':  70., # according to Koos et al. 2004, cited by Humphries et al., 2010, on avg 3 synpase per MSN-MSN connection
          'inDegSTNMSN':   0.,
          'inDegGPeMSN':   0.,
          'inDegCSNFSI':  50.,
          'inDegPTNFSI':   1.,
          'inDegSTNFSI':   2.,
          'inDegGPeFSI':  25.,
          'inDegCMPfFSI':  9.,
          'inDegFSIFSI':  15., # according to Humphries et al., 2010, 13-63 FSIs->FSI
          'inDegPTNSTN':  25.,
          'inDegCMPfSTN':  9.,
          'inDegGPeSTN':  25.,
          'inDegCMPfGPe':  9.,
          'inDegSTNGPe':   8.,
          'inDegMSNGPe':2644.,
          'inDegGPeGPe':  25.,
          'inDegMSNGPi':2644.,
          'inDegSTNGPi':   8.,
          'inDegGPeGPi':  23.,
          'inDegCMPfGPi':  9.,
          }
